# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cac8fb5312772abf4fd7796eb646d4b784c981f90a1afa9396cc2eeb4b4e70aa186ced681f4bcc3c5e899577b16bf8362b0757c3e0bbe458acd4746d8546962b

test:
  secret_key_base: 7f87c1ce46d03db505e4fa2962cbbb54ddfce4228566d03f8cf6f3d48b09c544fc5abd2c843551cf819c9cc22c7c511c27cb26a3810c0c9c187e6b6c77e1a730

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
